name: Build Test
 
on:
  push:
    branches: [ "main" ]
  pull_request: 

jobs: 
  build:
    name: Build Test
    runs-on: ubuntu-latest

    steps:
      - name: Get the source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Import vars example
        uses: zlatko-ms/varfiletoenv@v3
        with:
          paths: ./global.yml